os: Visual Studio 2015

install:
- dnvm upgrade -r clr
- dnu restore

before_build:
  - nuget restore

build:
  verbosity: minimal

build_script:
- cmd: dnu build ReflectionBridge\src\ReflectionBridge